const fontAwesome = {
  addressBook: "fa6-solid:address-book",
  barsStaggered: "fa6-solid:bars-staggered",
  book: "fa6-solid:book",
  bookOpenReader: "fa6-solid:book-open-reader",
  glasses: "fa6-solid:glasses",
  circleLeft: "fa6-solid:circle-left",
  circleRight: "fa6-solid:circle-right",
  circleXMark: "fa6-solid:circle-xmark",
  circleInfo: "fa6-solid:circle-info",
  circlePlay: "fa6-solid:circle-play",
  circlePlus: "fa6-solid:circle-plus",
  clockRotateLeft: "fa6-solid:clock-rotate-left",
  css3Alt: "fa6-brands:css3-alt",
  diagramProject: "fa6-solid:diagram-project",
  figma: "fa6-brands:figma",
  futbol: "fa6-solid:futbol",
  gamepad: "fa6-solid:gamepad",
  heart: "fa6-solid:heart",
  html5: "fa6-brands:html5",
  idCard: "fa6-solid:id-card",
  link: "fa6-solid:link",
  java: "fa6-brands:java",
  language: "fa6-solid:language",
  laptopCode: "fa6-solid:laptop-code",
  linkedin: "fa6-brands:linkedin",
  medal: "fa6-solid:medal",
  microsoft: "fa6-brands:microsoft",
  newspaper: "fa6-solid:newspaper",
  paintbrush: "fa6-solid:paintbrush",
  paperclip: "fa6-solid:paperclip",
  rankingStar: "fa6-solid:ranking-star",
  react: "fa6-brands:react",
  spinner: "fa6-solid:spinner",
  star: "fa6-solid:star",
  squareInstagram: "fa6-brands:square-instagram",
  squareGithub: "fa6-brands:square-github",
  squareJs: "fa6-brands:square-js",
  umbrellaBeach: "fa6-solid:umbrella-beach",
};

export default fontAwesome;
